### ISSUE TITLE
NoClassDefFoundError on GRPC classes after the Maven build is finished

### ISSUE THREAD

**Issue by cyrille-leclerc** [cyrille-leclerc/opentelemetry-maven-extension#1]
# Environment

* OpenTelemetry Maven Extension: https://github.com/cyrille-leclerc/opentelemetry-maven-extension/tree/0d7dfb117bd72596e98ac0f82e98ba02f198a3bd
* https://github.com/cyrille-leclerc/my-war with `pom.xml` modified like:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  ...
  <build>
        <extensions>
            <extension>
                <groupId>co.elastic.maven</groupId>
                <artifactId>opentelemetry-maven-extension</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </extension>
        </extensions>
  </build>
</project>
```

# Problem description
When the opentelemetry-maven-extension is configured as a `pom.xml` declaration  `<extension>`, there is for most executions a `NoClassDefFoundError` on a GRPC / Netty class.

This `NoClassDefFoundError` happens after the OpenTelemetry SDK is supposed to be shutdown suggesting the Maven classloader has unloaded the OpenTelemetry extension classes when a remaining GRPC activity is happening.

Example with https://github.com/cyrille-leclerc/opentelemetry-maven-extension/tree/0d7dfb117bd72596e98ac0f82e98ba02f198a3bd and https://github.com/cyrille-leclerc/my-war

Add to `pom.xml`:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  ...
  <build>
        <extensions>
            <extension>
                <groupId>co.elastic.maven</groupId>
                <artifactId>opentelemetry-maven-extension</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </extension>
        </extensions>
  </build>
</project>
```

```
export OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317
mvn -X verify
```

After the OpenTelemetry SDK an,d the OtlpGrpcSpanExporter is shutdown we see 
* a GRPC message being sent when the exporter should be shutdown completely `[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=`
* a `NoClassDefFoundError: io/grpc/netty/shaded/io/netty/channel/AbstractChannel$AbstractUnsafe$8`

logs:

```
[DEBUG] Close openTelemetrySdkService...
[INFO] Shutdown OTLP exporter...
[DEBUG] -Dio.grpc.netty.shaded.io.netty.leakDetection.level: simple
[DEBUG] -Dio.grpc.netty.shaded.io.netty.leakDetection.targetRecords: 4
[DEBUG] -Dio.grpc.netty.shaded.io.netty.buffer.checkAccessible: true
[DEBUG] -Dio.grpc.netty.shaded.io.netty.buffer.checkBounds: true
[DEBUG] Loaded default ResourceLeakDetector: io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector@1cfeee29
[DEBUG] -Dio.netty.allocator.numHeapArenas: 16
[DEBUG] -Dio.netty.allocator.numDirectArenas: 16
[DEBUG] -Dio.netty.allocator.pageSize: 8192
[DEBUG] -Dio.netty.allocator.maxOrder: 11
[DEBUG] -Dio.netty.allocator.chunkSize: 16777216
[DEBUG] -Dio.netty.allocator.smallCacheSize: 256
[DEBUG] -Dio.netty.allocator.normalCacheSize: 64
[DEBUG] -Dio.netty.allocator.maxCachedBufferCapacity: 32768
[DEBUG] -Dio.netty.allocator.cacheTrimInterval: 8192
[DEBUG] -Dio.netty.allocator.cacheTrimIntervalMillis: 0
[DEBUG] -Dio.netty.allocator.useCacheForAllThreads: true
[DEBUG] -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
[DEBUG] -Dio.netty.processId: 45492 (auto-detected)
[DEBUG] -Djava.net.preferIPv4Stack: false
[DEBUG] -Djava.net.preferIPv6Addresses: false
[DEBUG] Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
[DEBUG] Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
[DEBUG] -Dio.netty.machineId: ac:de:48:ff:fe:00:11:22 (auto-detected)
[DEBUG] -Dio.netty.allocator.type: pooled
[DEBUG] -Dio.netty.threadLocalDirectBufferSize: 0
[DEBUG] -Dio.netty.maxThreadLocalCharBufferSize: 16384
[DEBUG] -Dio.netty.recycler.maxCapacityPerThread: 4096
[DEBUG] -Dio.netty.recycler.maxSharedCapacityFactor: 2
[DEBUG] -Dio.netty.recycler.linkCapacity: 16
[DEBUG] -Dio.netty.recycler.ratio: 8
[DEBUG] -Dio.netty.recycler.delayedQueue.ratio: 8
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND SETTINGS: ack=false settings={MAX_FRAME_SIZE=16384}
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND SETTINGS: ack=true
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND SETTINGS: ack=true
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:4317, :path: /opentelemetry.proto.collector.trace.v1.TraceService/Export, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.39.0, grpc-accept-encoding: gzip, grpc-timeout: 9809809u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=722 bytes=00000002cd0aca050a350a170a0c736572766963652e6e616d6512070a056d6176656e0a1a0a0f736572766963652e76657273696f6e12070a05332e382e3212...
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=722
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND PING: ack=false bytes=145258749040133895
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND PING: ack=true bytes=145258749040133895
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc] padding=0 endStream=false
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND DATA: streamId=3 padding=0 endStream=false length=5 bytes=0000000000
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND PING: ack=false bytes=1234
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0, grpc-message: ] padding=0 endStream=true
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] INBOUND PING: ack=true bytes=1234
[INFO] OTLP exporter shut down in 276 ms
[INFO] Shutdown OTLP span exporter...
[INFO] OTLP span exporter shut down in 276 ms
[DEBUG] OpenTelemetrySdkService closed
[DEBUG] [id: 0x764e2524, L:/127.0.0.1:49919 - R:localhost/127.0.0.1:4317] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
[DEBUG] Maven session ended
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.412 s
[INFO] Finished at: 2021-08-16T16:04:59+02:00
[INFO] ------------------------------------------------------------------------
[WARNING] Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@3abd1e04(success)
java.lang.NoClassDefFoundError: io/grpc/netty/shaded/io/netty/channel/AbstractChannel$AbstractUnsafe$8
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.deregister (AbstractChannel.java:810)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister (AbstractChannel.java:770)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.close (AbstractChannel.java:753)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.close (AbstractChannel.java:608)
    at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.close (DefaultChannelPipeline.java:1352)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeClose (AbstractChannelHandlerContext.java:622)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.close (AbstractChannelHandlerContext.java:606)
    at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$ClosingChannelFutureListener.doClose (Http2ConnectionHandler.java:978)
    at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$ClosingChannelFutureListener.operationComplete (Http2ConnectionHandler.java:963)
    at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$ClosingChannelFutureListener.operationComplete (Http2ConnectionHandler.java:934)
    at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0 (DefaultPromise.java:577)
    at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow (DefaultPromise.java:551)
    at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners (DefaultPromise.java:490)
    at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.addListener (DefaultPromise.java:183)
    at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPromise.addListener (DefaultChannelPromise.java:95)
    at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPromise.addListener (DefaultChannelPromise.java:30)
    at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.doGracefulShutdown (Http2ConnectionHandler.java:493)
    at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.close (Http2ConnectionHandler.java:477)
    at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.close (NettyClientHandler.java:431)
    at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.gracefulClose (NettyClientHandler.java:780)
    at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.write (NettyClientHandler.java:345)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite0 (AbstractChannelHandlerContext.java:717)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeWrite (AbstractChannelHandlerContext.java:709)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write (AbstractChannelHandlerContext.java:792)
    at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.write (AbstractChannelHandlerContext.java:702)
    at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.write
```

Detailed logs: https://github.com/cyrille-leclerc/my-war and https://gist.github.com/cyrille-leclerc/208067cb781634ddfc5052dd68c2cb0c

**Comment by cyrille-leclerc** [comment]
Problem raised to the opentelemetry-java project https://github.com/open-telemetry/opentelemetry-java/issues/3521

**Comment by cyrille-leclerc** [comment]
With support for multi-module maven projects + cleanup 

https://github.com/cyrille-leclerc/opentelemetry-maven-extension/tree/9071b1cba56c3f5d4c33b2d1b6f88cbee558e45a

```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ opentelemetry-maven-extension ---
[INFO] Installing /Users/cyrilleleclerc/git/maven/opentelemetry-maven-extension/target/opentelemetry-maven-extension-0.1.0-SNAPSHOT.jar to /Users/cyrilleleclerc/.m2/repository/co/elastic/maven/opentelemetry-maven-extension/0.1.0-SNAPSHOT/opentelemetry-maven-extension-0.1.0-SNAPSHOT.jar
[INFO] Installing /Users/cyrilleleclerc/git/maven/opentelemetry-maven-extension/dependency-reduced-pom.xml to /Users/cyrilleleclerc/.m2/repository/co/elastic/maven/opentelemetry-maven-extension/0.1.0-SNAPSHOT/opentelemetry-maven-extension-0.1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.509 s
[INFO] Finished at: 2021-08-28T17:11:02+02:00
[INFO] ------------------------------------------------------------------------
Exception in thread "BatchSpanProcessor_WorkerThread-1" java.lang.NoClassDefFoundError: io/grpc/internal/ManagedChannelImpl$1NotifyStateChanged
        at io.grpc.internal.ManagedChannelImpl.notifyWhenStateChanged(ManagedChannelImpl.java:1316)
        at io.grpc.internal.ForwardingManagedChannel.notifyWhenStateChanged(ForwardingManagedChannel.java:78)
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter.shutdown(OtlpGrpcSpanExporter.java:189)
        at co.elastic.maven.opentelemetry.MyOtlpGrpcSpanExporter.shutdown(MyOtlpGrpcSpanExporter.java:51)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.lambda$shutdown$2(BatchSpanProcessor.java:268)
        at io.opentelemetry.sdk.common.CompletableResultCode.succeed(CompletableResultCode.java:85)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.flush(BatchSpanProcessor.java:253)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:216)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.grpc.internal.ManagedChannelImpl$1NotifyStateChanged
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 9 more
[WARNING] OpenTelemetry: Failure to shutdown SDK Trace Provider in 10005 ms, done: false success: false
[WARNING] Problem disposing: co.elastic.maven.opentelemetry.OpenTelemetrySdkService@5d1206e0
java.lang.NoClassDefFoundError: io/grpc/internal/ManagedChannelImpl$1NotifyStateChanged
    at io.grpc.internal.ManagedChannelImpl.notifyWhenStateChanged (ManagedChannelImpl.java:1316)
    at io.grpc.internal.ForwardingManagedChannel.notifyWhenStateChanged (ForwardingManagedChannel.java:78)
    at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter.shutdown (OtlpGrpcSpanExporter.java:189)
    at co.elastic.maven.opentelemetry.MyOtlpGrpcSpanExporter.close (MyOtlpGrpcSpanExporter.java:59)
    at co.elastic.maven.opentelemetry.OpenTelemetrySdkService.dispose (OpenTelemetrySdkService.java:76)
    at org.eclipse.sisu.plexus.PlexusLifecycleManager.dispose (PlexusLifecycleManager.java:368)
    at org.eclipse.sisu.plexus.PlexusLifecycleManager.unmanage (PlexusLifecycleManager.java:173)
    at org.codehaus.plexus.DefaultPlexusContainer.dispose (DefaultPlexusContainer.java:590)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:320)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```
